import { SpeakerPhotoGridType } from "../../components/Speakers/SpeakersGrid/speakerGrid.types";

export const SPEAKERFULLGRID_MENU: Record<string, SpeakerPhotoGridType> = {
  s1: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker1.webp",
  },

  s2: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker2.webp",
  },
  s3: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker3.webp",
  },
  s4: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker1.webp",
  },
  s5: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker2.webp",
  },
  s6: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker3.webp",
  },
  s7: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker1.webp",
  },
  s8: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker2.webp",
  },
  s9: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker1.webp",
  },

  s10: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker2.webp",
  },
  s11: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker3.webp",
  },
  s12: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker1.webp",
  },
  s13: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker2.webp",
  },
  s14: {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    companyOfWork: "LLorem ipsum dolor sit amet.",
    position: "Lorem Ipsum",
    disabled: false,
    src: "/images/speaker3.webp",
  },
};
