import { SpeakerPhotoGridType } from "../../components/Speakers/SpeakersGrid/speakerGrid.types";

export const SPEAKERFULLGRID_MENU: Record<string, SpeakerPhotoGridType> = {
  will: {
    id: "will-stevens",
    name: "Will Stevens",
    companyOfWork: "U.S. Consulate General Lagos",
    position: "Consul General",
    disabled: false,
    src: "/images/will.webp",
  },

  oyin: {
    id: "oyin-solebo",
    name: "Oyin Solebo",
    companyOfWork: "Techstars Lagos",
    position: "Managing Director",
    disabled: false,
    src: "/images/oyin.webp",
  },
  somachi: {
    id: "somachi",
    name: "Somachi Chris-Asoluka",
    companyOfWork: "The Tony Elumelu Foundation",
    position: "Chief Executive Officer",
    disabled: false,
    src: "/images/somachi.webp",
  },
  bernard: {
    id: "bernard",
    name: "Bernard Ghartey",
    companyOfWork: "Norrsken22",
    position: "Investment Manager",
    disabled: false,
    src: "/images/bernard.webp",
  },
  satoshi: {
    id: "satoshi",
    name: "Satoshi Shinada",
    companyOfWork: "Verod Kepple Africa Ventures",
    position: "Partner",
    disabled: false,
    src: "/images/satoshi.webp",
  },
  joshua: {
    id: "joshua",
    name: "Joshua Chibueze",
    companyOfWork: "Co-founder and Chief Marketing Officer ",
    position: "Piggyvest",
    disabled: false,
    src: "/images/joshua.webp",
  },
  ore: {
    id: "ore",
    name: "Ore Ogunbiyi",
    companyOfWork: "The Economist",
    position: "Africa Correspondent",
    disabled: false,
    src: "/images/ore.webp",
  },
  nnaemeka: {
    id: "nnaemeka",
    name: "Nnaemeka Clinton",
    companyOfWork: "Spark",
    position: "Chief Executive Officer",
    disabled: false,
    src: "/images/nnaemeka.webp",
  },
  blessing: {
    id: "blessing",
    name: "Blessing Abeng",
    companyOfWork: "",
    position: "Branding and Communications Expert",
    disabled: false,
    src: "/images/blessing.webp",
  },
  uwem: {
    id: "uwem",
    name: "Uwem Uwemakpan ",
    companyOfWork: "Launch Africa VC.",
    position: "Head of Investment",
    disabled: false,
    src: "/images/uwem.webp",
  },
  ike: {
    id: "ike",
    name: "Ike Eze",
    companyOfWork: "Beta Ventures",
    position: "Managing Partner",
    disabled: false,
    src: "/images/ike.png",
  },
  omoruyi: {
    id: "omoruyi",
    name: "Omoruyi Edoigiawerie",
    companyOfWork: "E & C Legal",
    position: "Lead Partner / Chief Servant",
    disabled: false,
    src: "/images/omoruyi.webp",
  },
  babajide: {
    id: "babajide",
    name: "Babajide Duroshola",
    companyOfWork: "M-KOPA",
    position: "General Manager",
    disabled: false,
    src: "/images/babajide.webp",
  },
  mohini: {
    id: "mohini",
    name: "Mohini Ufeli-Ezekwesili",
    companyOfWork: "Paystack",
    position: "Marketing Manager",
    disabled: false,
    src: "/images/mohini.webp",
  },
  obinna: {
    id: "obinna",
    name: "Obinna Ukachukwu",
    companyOfWork: "Sterling Bank",
    position: "Growth Executive",
    disabled: false,
    src: "/images/obinna.webp",
  },
  jordy: {
    id: "jordy",
    name: "Jordy Kiange Beni",
    companyOfWork: "Octerra Capital",
    position: "Investment Principal",
    disabled: false,
    src: "/images/jordy.webp",
  },
  alyune: {
    id: "alyune",
    name: "Alyune-Blondin Diop",
    companyOfWork: "LoftyInc Capital",
    position: "Senior Investment Associate",
    disabled: false,
    src: "/images/alyune.webp",
  },
};
