import Image from "next/image";
import './directHeroImport.styles.css';

export const DirectHeroImport = () => {
  // const Word1 = "Discover".split("");
  // const Word2 = "Culinary Secrets".split(" ");
  // const Word3 = "at our festival".split(" ");
  return (
    <section
      className="elementor-section elementor-top-section elementor-element elementor-element-359d652 elementor-section-full_width elementor-section-height-default elementor-section-height-default sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited"
      data-id="359d652"
      data-element_type="section"
    >
      <div className="elementor-container elementor-column-gap-extended">
        <div
          className="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7b72279 sc_inner_width_none sc_content_align_inherit sc_layouts_column_icons_position_left sc_fly_static trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited"
          data-id="7b72279"
          data-element_type="column"
        >
          <div className="elementor-widget-wrap elementor-element-populated">
            <div
              className="elementor-element elementor-element-9301414 sc_fly_static elementor-widget elementor-widget-trx_widget_slider trx_addons_parallax_layers_inited trx_addons_parallax_blocks_inited"
              data-id="9301414"
              data-element_type="widget"
              data-widget_type="trx_widget_slider.default"
            >
              <div className="elementor-widget-container">
                <div className="widget_area sc_widget_slider">
                  <aside className="widget widget_slider">
                    <div className="slider_wrap slider_engine_revo slider_alias_slider-3">
                      <div className="wp-block-themepunch-revslider 0">
                        <rs-fullwidth-wrap
                          id="rev_slider_19_1_forcefullwidth"

                        >
                          <rs-module-wrap
                            id="rev_slider_19_1_wrapper"
                            data-source="gallery"
                          >
                            <rs-module
                              id="rev_slider_19_1"
                              data-version="6.7.18"
                              data-idcheck="true"
                              className="revslider-initialised rev_redraw_on_blurfocus"
                              data-slideactive="rs-47"
                            >
                              <rs-static-layers data-key="staticlayers"></rs-static-layers>
                              <rs-progress >
                                <rs-progress-bar ></rs-progress-bar>
                              </rs-progress>
                              <rs-slides >
                                <rs-slide
                                  data-key="rs-47"
                                  data-title="Slide"
                                  data-anim="ms:1000ms;"
                                  data-in="o:0;"
                                  data-out="a:false;"
                                  data-originalindex="1"
                                  data-origindex="0"
                                  data-description=""
                                  data-sba=""
                                  data-scroll-based="false"
                                  data-owidth="300"
                                  data-oheight="200"
                                  data-rspausetimeronce="0"
                                  data-isactiveslide="true"
                                >
                                  <rs-sbg-px>
                                    <rs-sbg-wrap
                                      data-key="rs-47"
                                      data-owidth="300"
                                      data-oheight="200"
                                    >
                                      <rs-sbg
                                        data-lazyload="//agora.ancorathemes.com/wp-content/plugins/revslider/sr6/assets/assets/transparent.png"
                                        className=""
                                        data-bgcolor="transparent"
                                        data-src-rs-ref="//agora.ancorathemes.com/wp-content/plugins/revslider/sr6/assets/assets/transparent.png"
                                      >
                                        <canvas
                                          width="944"
                                          height="446"
                                        ></canvas>
                                      </rs-sbg>
                                    </rs-sbg-wrap>
                                  </rs-sbg-px>

                                  <rs-zone
                                    id="rrzm_47"
                                    className="rev_row_zone_middle"
                                    data-middle="true"
                                  >
                                    <rs-row-wrap
                                      className="rs-parallax-wrap slider-row-wrap"
                                    >
                                      <rs-row
                                        id="slider-19-slide-47-layer-15"
                                        data-type="row"
                                        data-xy="xo:50px;yo:50px;"
                                        data-cbreak="nobreak"
                                        data-basealign="slide"
                                        data-wrpcls="slider-row-wrap"
                                        data-rsp_bd="off"
                                        data-margin="r:70,0,0,20;b:0,0,0,50;l:140,70,30,20;"
                                        data-frame_0="o:1;"
                                        data-frame_999="o:0;st:w;sR:8700;sA:9000;"
                                        className="rs-layer"
                                        data-idcheck="true"
                                        data-initialised="true"
                                      >
                                        <rs-column-wrap
                                          className="rs-parallax-wrap"
                                        >
                                          <rs-column
                                            id="slider-19-slide-47-layer-16"
                                            data-type="column"
                                            data-xy="xo:50px;yo:50px;"
                                            data-text="l:20,25,25,6;"
                                            data-rsp_bd="off"
                                            data-column="w:100%;a:middle;"
                                            data-frame_0="o:1;"
                                            data-frame_999="o:0;st:w;sR:8700;sA:9000;"
                                            className="rs-layer"
                                            data-idcheck="true"
                                            data-initialised="true"
                                          >
                                            <rs-layer-wrap
                                              className="rs-parallax-wrap rs-layer-hidden wrap-1"
                                            >
                                              <rs-mask-wrap>
                                                <rs-layer
                                                  id="slider-19-slide-47-layer-7"
                                                  data-type="image"
                                                  data-rsp_ch="on"
                                                  data-xy="xo:50px,37px,19px,0;yo:50px,37px,19px,0;"
                                                  data-pos="r"
                                                  data-text="w:normal;s:20,15,8,4;l:0,18,9,6;"
                                                  data-dim="w:31px,23px,12px,100%;h:33px,24px,12px,auto;"
                                                  data-vbility="f,f,f,t"
                                                  data-frame_0="y:105%;o:1;skY:2px;"
                                                  data-frame_0_mask="u:t;y:-90%;"
                                                  data-frame_1="e:power2.out;st:300;sp:1200;sR:300;"
                                                  data-frame_1_mask="u:t;"
                                                  data-frame_999="o:0;st:w;sR:7500;"
                                                  className="rs-layer"
                                                  data-idcheck="true"
                                                  data-initialised="true"
                                                >
                                                  <img
                                                    loading="lazy"
                                                    decoding="async"
                                                    src="//agora.ancorathemes.com/wp-content/uploads/2024/04/230_3-1-copyright.jpg"
                                                    alt=""
                                                    className="tp-rs-img rs-lazyload"
                                                    width="875"
                                                    height="920"
                                                    data-lazyload="//agora.ancorathemes.com/wp-content/uploads/2024/04/230_3-1-copyright.jpg"
                                                    data-no-retina=""
                                                    data-src-rs-ref="//agora.ancorathemes.com/wp-content/uploads/2024/04/230_3-1-copyright.jpg"
                                                  />
                                                </rs-layer>
                                              </rs-mask-wrap>
                                            </rs-layer-wrap>
                                            <rs-layer-wrap
                                              className="rs-parallax-wrap wrap-2"
                                            >
                                              <rs-layer
                                                id="slider-19-slide-47-layer-6"
                                                data-type="shape"
                                                data-rsp_ch="on"
                                                data-xy="xo:50px,37px,19px,11px;yo:50px,37px,19px,11px;"
                                                data-pos="r"
                                                data-text="w:normal;s:20,15,8,4;c:both;l:0,18,9,6;"
                                                data-flcr="c:both;"
                                                data-dim="w:100%;h:10px,7px,3px,24px;"
                                                data-frame_999="o:0;st:w;sR:8700;"
                                                className="rs-layer"
                                                data-idcheck="true"
                                                data-initialised="true"
                                              ></rs-layer>
                                            </rs-layer-wrap>
                                            <rs-layer-wrap
                                              className="rs-parallax-wrap wrap-3"
                                            >
                                              <rs-layer
                                                id="slider-19-slide-47-layer-8"
                                                data-type="text"
                                                data-xy="xo:560px,440px,300px,360px;yo:60px,50px,30px,500px;"
                                                data-pos="a"
                                                data-text="w:normal;s:20,15,8,4;l:25,18,9,6;"
                                                data-dim="w:76px,67px,50px,56px;"
                                                data-frame_0="sX:0.9;sY:0.9;"
                                                data-frame_1="st:1060;sp:1000;sR:1060;"
                                                data-frame_999="o:0;st:w;sR:6940;"
                                                className="rs-layer"
                                                data-idcheck="true"
                                                data-initialised="true"
                                              >
                                                <svg
                                                  xmlns="http://www.w3.org/2000/svg"
                                                  xmlnsXlink="http://www.w3.org/1999/xlink"
                                                  width="100%"
                                                  height="100%"
                                                  viewBox="0 0 76.354 78.024"
                                                >
                                                  <defs>
                                                    <clipPath id="clip-path">
                                                      <rect
                                                        id="Rectangle_33604"
                                                        data-name="Rectangle 33604"
                                                        width="60.559"
                                                        height="63.074"
                                                        transform="translate(0 0)"
                                                        fill="#fd4c19"
                                                      ></rect>
                                                    </clipPath>
                                                  </defs>
                                                  <g
                                                    id="element"
                                                    transform="translate(-688.102 -409.202)"
                                                  >
                                                    <g
                                                      id="Group_44344"
                                                      data-name="Group 44344"
                                                      transform="translate(688.103 426.908) rotate(-17)"
                                                      clipPath="url(#clip-path)"
                                                    >
                                                      <path
                                                        id="Path_210090"
                                                        data-name="Path 210090"
                                                        d="M13.218.569A6.534,6.534,0,0,0,4.643,3.813C1.711,10.093.476,20.232.006,25.6a1.4,1.4,0,0,0,2.377,1.127C6.274,22.943,13.415,15.5,16.391,9.234A6.47,6.47,0,0,0,13.218.569"
                                                        fill="#fd4c19"
                                                      ></path>
                                                      <path
                                                        id="Path_210091"
                                                        data-name="Path 210091"
                                                        d="M59.609,11.276A9.662,9.662,0,0,0,46.8,6.827c-9.283,4.346-20.3,14.681-25.926,20.332a2.075,2.075,0,0,0,1.63,3.533c8.007-.609,23.167-2.282,32.487-6.575a9.566,9.566,0,0,0,4.616-12.841"
                                                        fill="#fd4c19"
                                                      ></path>
                                                      <path
                                                        id="Path_210092"
                                                        data-name="Path 210092"
                                                        d="M53.309,58.285a7.037,7.037,0,0,0-4.465-8.805c-7.062-2.413-18.059-2.562-23.865-2.444a1.511,1.511,0,0,0-.931,2.676c4.5,3.727,13.3,10.512,20.352,12.971a6.965,6.965,0,0,0,8.909-4.4"
                                                        fill="#fd4c19"
                                                      ></path>
                                                    </g>
                                                  </g>
                                                </svg>
                                              </rs-layer>
                                            </rs-layer-wrap>
                                            <rs-layer-wrap
                                              className="rs-parallax-wrap wrap-4"
                                            >
                                              <rs-layer
                                                id="slider-19-slide-47-layer-24"
                                                data-type="text"
                                                data-color="#fd4c19"
                                                data-xy=""
                                                data-pos="r"
                                                data-text="w:normal;s:90,70,50,60;l:90,70,50,58;ls:-1px;fw:500;"
                                                data-rsp_o="off"
                                                data-disp="inline-block"
                                                data-frame_0="o:1;"
                                                data-frame_0_chars="d:5;y:30%;o:0;rY:0deg;rZ:0deg;"
                                                data-frame_1="e:power3.out;st:430;sp:1200;sR:430;"
                                                data-frame_1_chars="e:power3.out;d:2;rZ:0deg;"
                                                data-frame_999="o:0;st:w;sR:6650;"
                                                className="rs-layer"
                                                data-idcheck="true"
                                                data-initialised="true"
                                              >
                                                <div
                                                  className="rs_splitted_lines"
                                                >
                                                  <div
                                                    className="rs_splitted_words"
                                                  >
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      D
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      i
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      s
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      c
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      o
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      v
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      e
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      r
                                                    </div>
                                                  </div>
                                                </div>
                                                <div
                                                  className="rs_splitted_lines"
                                                >
                                                  <div
                                                    className="rs_splitted_words"
                                                  >
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      c
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      u
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      l
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      i
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      n
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      a
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      r
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      y
                                                    </div>
                                                  </div>
                                                  <div
                                                    className="rs_splitted_words"
                                                  >
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      s
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      e
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      c
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      r
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      e
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      t
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      s
                                                    </div>
                                                  </div>
                                                </div>
                                                <div
                                                  className="rs_splitted_lines"
                                                >
                                                  <div
                                                    className="rs_splitted_words"
                                                  >
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      a
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      t
                                                    </div>
                                                  </div>
                                                  <div
                                                    className="rs_splitted_words"
                                                  >
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      o
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      u
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      r
                                                    </div>
                                                  </div>
                                                  <div
                                                    className="rs_splitted_words"
                                                  >
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      f
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      e
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      s
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      t
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      i
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      v
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      a
                                                    </div>
                                                    <div
                                                      className="rs_splitted_chars"
                                                    >
                                                      l
                                                    </div>
                                                  </div>
                                                </div>
                                              </rs-layer>
                                            </rs-layer-wrap>
                                            <rs-layer-wrap
                                              className="rs-parallax-wrap wrap-5"
                                            >
                                              <rs-layer
                                                id="slider-19-slide-47-layer-5"
                                                data-type="shape"
                                                data-rsp_ch="on"
                                                data-xy="xo:50px,37px,19px,11px;yo:373px,279px,150px,92px;"
                                                data-pos="r"
                                                data-text="w:normal;s:20,15,8,4;c:both;l:0,18,9,6;"
                                                data-flcr="c:both;"
                                                data-dim="w:100%;h:160px,120px,0px,0px;"
                                                data-frame_999="o:0;st:w;sR:8700;"
                                                className="rs-layer"
                                                data-idcheck="true"
                                                data-initialised="true"
                                              ></rs-layer>
                                            </rs-layer-wrap>
                                          </rs-column>
                                        </rs-column-wrap>
                                      </rs-row>
                                    </rs-row-wrap>
                                  </rs-zone>
                                  <rs-zone
                                    id="rrzb_47"
                                    className="rev_row_zone_bottom"
                                  >
                                    <rs-row-wrap
                                      className="rs-parallax-wrap slider-row-wrap"
                                    >
                                      <rs-row
                                        id="slider-19-slide-47-layer-1"
                                        data-type="row"
                                        data-xy="xo:50px;yo:50px;"
                                        data-cbreak="nobreak"
                                        data-basealign="slide"
                                        data-wrpcls="slider-row-wrap"
                                        data-rsp_bd="off"
                                        data-margin="r:70,0,0,0;l:140,70,30,20;"
                                        data-padding="b:0,0,10,10;"
                                        data-frame_0="o:1;"
                                        data-frame_999="o:0;st:w;sR:8700;sA:9000;"
                                        className="rs-layer"
                                        data-idcheck="true"
                                        data-initialised="true"
                                      >
                                        <rs-column-wrap
                                          className="rs-parallax-wrap"
                                        >
                                          <rs-column
                                            id="slider-19-slide-47-layer-2"
                                            data-type="column"
                                            data-xy="xo:50px;yo:50px;"
                                            data-text="l:20,25,25,25;"
                                            data-rsp_bd="off"
                                            data-column="w:100%;a:middle;"
                                            data-frame_0="o:1;"
                                            data-frame_999="o:0;st:w;sR:8700;sA:9000;"
                                            className="rs-layer"
                                            data-idcheck="true"
                                            data-initialised="true"
                                          >
                                            <rs-layer-wrap
                                              className="rs-parallax-wrap"
                                            >
                                              <rs-layer
                                                id="slider-19-slide-47-layer-4"
                                                data-type="text"
                                                data-color="#363332"
                                                data-xy="xo:220px,155px,156px,156px;y:m;yo:-18px,-22px,-22px,-22px;"
                                                data-pos="a"
                                                data-text="w:normal;s:17,16,16,16;l:26,23,23,23;"
                                                data-dim="w:311px,210px,210px,210px;"
                                                data-vbility="t,t,f,f"
                                                data-rsp_o="off"
                                                data-rsp_bd="off"
                                                data-frame_0="x:10%;"
                                                data-frame_1="st:1450;sp:1000;sR:1450;"
                                                data-frame_999="o:0;st:w;sR:6550;"
                                                className="rs-layer"
                                                data-idcheck="true"
                                                data-initialised="true"
                                              >
                                                Sed ut perspiciatis unde omnis
                                                iste natus error sit voluptatem
                                                accusantium
                                              </rs-layer>
                                            </rs-layer-wrap>
                                            <rs-layer-wrap
                                              className="rs-parallax-wrap"
                                            >
                                              <a
                                                id="slider-19-slide-47-layer-3"
                                                className="rs-layer sldr-btn-icon"
                                                href="/event/the-cookout-festival/"
                                                target="_self"
                                                data-type="text"
                                                data-color="#fd4c19"
                                                data-xy="xo:220px,155px,0,0;y:m,m,b,b;yo:35px,37px,0,0;"
                                                data-pos="a"
                                                data-text="w:normal;s:17,15,15,15;fw:500;"
                                                data-rsp_o="off"
                                                data-rsp_bd="off"
                                                data-frame_0="x:10%;"
                                                data-frame_1="st:1740;sp:1000;sR:1740;"
                                                data-frame_999="o:0;st:w;sR:6260;"
                                                data-idcheck="true"
                                                data-initialised="true"
                                              >
                                                Buy Tickets
                                              </a>
                                            </rs-layer-wrap>
                                            <rs-layer-wrap
                                              className="rs-parallax-wrap"
                                            >
                                              <rs-mask-wrap>
                                                <rs-layer
                                                  id="slider-19-slide-47-layer-0"
                                                  data-type="image"
                                                  data-xy="xo:266px;yo:695px;"
                                                  data-pos="r"
                                                  data-text="w:normal;"
                                                  data-dim="w:180px,131px,131px,131px;h:160px,116px,116px,116px;"
                                                  data-vbility="t,t,f,f"
                                                  data-rsp_o="off"
                                                  data-rsp_bd="off"
                                                  data-frame_0="x:105%;y:0%;o:1;skY:2px;"
                                                  data-frame_0_mask="u:t;x:-90%;"
                                                  data-frame_1="e:power4.out;st:1340;sp:1200;sR:1340;"
                                                  data-frame_1_mask="u:t;"
                                                  data-frame_999="o:0;st:w;sR:6460;"
                                                  className="rs-layer"
                                                  data-idcheck="true"
                                                  data-initialised="true"
                                                >
                                                  <Image
                                                    loading="lazy"
                                                    decoding="async"
                                                    src="/images/copyright.jpg"
                                                    alt=""
                                                    className="tp-rs-img rs-lazyload"
                                                    width="180"
                                                    height="160"
                                                    data-lazyload="//agora.ancorathemes.com/wp-content/uploads/2024/04/230_3-2-copyright.jpg"
                                                    data-no-retina=""
                                                    data-src-rs-ref="//agora.ancorathemes.com/wp-content/uploads/2024/04/230_3-2-copyright.jpg"
                                                  />
                                                </rs-layer>
                                              </rs-mask-wrap>
                                            </rs-layer-wrap>
                                          </rs-column>
                                        </rs-column-wrap>
                                      </rs-row>
                                    </rs-row-wrap>
                                  </rs-zone>
                                  <rs-layer-wrap
                                    className="rs-parallax-wrap sldr-img"
                                  >
                                    <rs-mask-wrap>
                                      <rs-layer
                                        id="slider-19-slide-47-layer-52"
                                        data-type="image"
                                        data-xy="x:r;xo:70px,70px,29px,29px;y:m;yo:20px,0,0,0;"
                                        data-text="w:normal;s:20,15,8,4;l:0,18,9,6;"
                                        data-dim="w:875px,656px,333px,333px;h:920px,690px,350px,350px;"
                                        data-vbility="t,t,t,f"
                                        data-rsp_o="off"
                                        data-wrpcls="sldr-img"
                                        data-margin="l:-20,-15,-8,-5;"
                                        data-frame_0="y:105%;o:1;skY:2px;"
                                        data-frame_0_mask="u:t;y:-90%;"
                                        data-frame_1="e:power2.out;st:300;sp:1200;sR:300;"
                                        data-frame_1_mask="u:t;"
                                        data-frame_999="o:0;st:w;sR:7500;"
                                        className="rs-layer"
                                        data-idcheck="true"
                                        data-initialised="true"
                                      >
                                        <Image
                                          loading="lazy"
                                          decoding="async"
                                          src="/images/newHero.jpg"
                                          alt=""
                                          className="tp-rs-img rs-lazyload"
                                          width="875"
                                          height="920"
                                          data-lazyload="//agora.ancorathemes.com/wp-content/uploads/2024/04/230_3-1-copyright.jpg"
                                          data-no-retina=""
                                          data-src-rs-ref="//agora.ancorathemes.com/wp-content/uploads/2024/04/230_3-1-copyright.jpg"
                                        />
                                      </rs-layer>
                                    </rs-mask-wrap>
                                  </rs-layer-wrap>
                                </rs-slide>
                              </rs-slides>
                            </rs-module>

                            {/*<script>*/}
                            {/*  setREVStartSize({c: 'rev_slider_19_1',rl:[1240,1460,785,500],el:[840,680,350,1113],gw:[1920,1440,778,480],gh:[840,680,350,400],type:'hero',justify:'',layout:'fullwidth',mh:"0"});if*/}
                            {/*  (window.RS_MODULES!==undefined && window.RS_MODULES.modules!==undefined &&*/}
                            {/*  window.RS_MODULES.modules["revslider191"]!==undefined) {window.RS_MODULES.modules["revslider191"].once = false;window.revapi19 = undefined;if (window.RS_MODULES.checkMinimal!==undefined) window.RS_MODULES.checkMinimal()}*/}
                            {/*</script>*/}
                          </rs-module-wrap>
                          <rs-fw-forcer style={{height: '446px'}}></rs-fw-forcer>
                        </rs-fullwidth-wrap>
                      </div>
                    </div>
                  </aside>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
